# Generated by Django 5.1.6 on 2025-02-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_question_votes_alter_view_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_question_vote',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_answer_vote',
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='answer',
        ),
        migrations.AlterField(
            model_name='view',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myapp.question'),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='question_votes', through='myapp.QuestionVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='view',
            name='session_id',
        ),
    ]
